export const UPDATE_FORM_DATA = 'FORM/UPDATE_FORM_DATA';
export const RESET_FORM_DATA = 'FORM/RESET_FORM_DATA';

export const UPDATE_SCORE = 'LEADER_BOARD/UPDATE_SCORE';
export const UPDATE_USER = 'LEADER_BOARD/UPDATE_USER';


